# Generated by Django 4.1.5 on 2023-07-13 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuarios_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='data_postagem',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 4, 53, 15, 206418)),
        ),
    ]
