# Generated by Django 4.1.5 on 2023-07-19 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_access_delete_acesso_alter_usuarios_data_postagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='data_postagem',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 15, 39, 59, 505560)),
        ),
    ]
