# Use uma imagem base do Python, por exemplo, para um projeto Django
FROM python:3.8

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos da pasta local para dentro do container no diretório /app
COPY C:\Users\Windows\10\Documents\PORTFOLIO\dev_portfolio\portfolio_g\core\migrations /app

# Instala as dependências do projeto, caso necessário
# RUN pip install -r requirements.txt